# Local Inventory for Docker Compose Kafka Cluster
# Usage: docker-compose up -d && docker exec -it kafka-perf-test bash
#        ansible-playbook -i inventories/local playbooks/producer_baseline.yml

all:
  children:
    kafka_broker:
      hosts:
        kafka-perf-test:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

    test_hosts:
      hosts:
        kafka-perf-test:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

  vars:
    # Kafka cluster connection (internal docker network)
    kafka_broker:
      hosts:
        - "kafka-broker-1:29092"
        - "kafka-broker-2:29093"
        - "kafka-broker-3:29094"

    # No SSL for local testing
    ssl_enabled: false

    # Kafka binary location in container
    kafka_home: "/opt/kafka"
    binary_base_path: "/opt/kafka"

    # Results directory (mounted volume)
    results_base_path: "/app/results"

    # Test topic configuration (smaller for local testing)
    perf_topic_name: "perf-test-local"
    perf_replication_factor: 3
    perf_partitions: 12

    # Reduced test parameters for local testing
    perf_num_records: 100000
    perf_record_size: 1024

    # Default test profile
    test_profile: "quick"

    # Script paths (absolute for docker)
    scripts_dir: "/app/scripts"
    use_venv: false
    python_executable: "python3"

    # Results directory (absolute for docker)
    results_base_dir: "/app/results"
    raw_logs_dir: "/app/results/raw_logs"
    parsed_data_dir: "/app/results/parsed_data"
    reports_dir: "/app/results/reports"
