all:
  hosts:
  children:
    kafka_broker:
      hosts:
        kafka-broker-1.dev: #Amnend the hostname
          broker_id: 0
        kafka-broker-2.dev: #Amnend the hostname
          broker_id: 1
        kafka-broker-3.dev: #Amnend the hostname
          broker_id: 2